name: run-tests

on: [push, pull_request]


jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP 8.1 test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
      - name: Install dependencies
        run: |
          composer install
      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
